- name: Ensure Git is installed
  package:
    name: git
    state: present

- name: Ensure Zig is installed
  package:
    name: zig
    state: present

- name: Clone the Git repository
  git:
    repo: "https://github.com/user/repo.git"
    dest: "/tmp/repo"
    force: yes

- name: Build the project with Zig
  command: sudo zig build -p /usr/local -Doptimize=ReleaseFast
  args:
    chdir: /tmp/repo

- name: Remove the cloned repository
  file:
    path: "/tmp/repo"
    state: absent
